kind: pipeline
type: docker
name: default

steps:
- name: build
  image: alpine
  environment:
    DOCKER_HUB_PASSWORD:
      from_secret: docker_hub_password
  commands:
    - echo "The build number is:"
    - echo $DRONE_BUILD_NUMBER

- name: docker
  image: plugins/docker
  settings:
    username: boulundeasv
    password:
      from_secret: docker_hub_password
    repo: boulundeasv/demo-website
    tags:
    - latest
    - ${DRONE_BUILD_NUMBER}
    - staging

trigger:
  event:
  - push
  branch:
  - main

---

kind: pipeline
type: docker
name: deploy

steps:
- name: Deploy frontend deployment
  image: alpine
  commands:
    - echo "Promoting build"
    - echo $DRONE_TAG
  trigger:
    event:
      - promote
      - rollback
    target:
      - production