kind: pipeline
type: docker
name: default

trigger:
  event:
  - push
  branch:
  - main

steps:
- name: build
  image: alpine
  environment:
    DOCKER_HUB_PASSWORD:
      from_secret: docker_hub_password
  commands:
    - echo "The build number is:"
    - echo $DRONE_BUILD_NUMBER

  # Store a file artifact
- name: store_artifact
  image: alpine
  commands:
    - echo "Storing artifact..."
    - echo "This is an artifact file." > artifact.txt

- name: docker
  image: plugins/docker
  settings:
    username: boulundeasv
    password:
      from_secret: docker_hub_password
    repo: boulundeasv/demo-website
    tags:
    - latest
    - ${DRONE_BUILD_NUMBER}
    - staging

---

kind: pipeline
type: docker
name: deploy

trigger:
  event:
    - promote

steps:
- name: docker
  image: plugins/docker
  settings:
    username: boulundeasv
    password:
      from_secret: docker_hub_password
    repo: boulundeasv/demo-website
    tags:
    - production

artifact:
  path: artifact.txt