kind: pipeline
type: docker
name: default

steps:
# - name: test
#   image: mcr.microsoft.com/dotnet/sdk
#   commands:
#   - dotnet build
#   - dotnet test
# - name: deliver
#   image: docker:dind
#   commands:
#   - sleep 5 # give docker enough time to start
#   - docker ps -a
#   - docker run -d hello-world
#   - docker ps -a

steps:
- name: build
  image: alpine
  environment:
    DOCKER_HUB_PASSWORD:
      from_secret: docker_hub_password
  commands:
    - echo "You can call the secrets like this examples below."
    - echo $DOCKER_HUB_PASSWORD
    - echo "In both cases, and for security reasons, you will see asteriks '*******' instead the value under the echo command."

- name: docker
  image: plugins/docker
  environment:
    DOCKER_HUB_PASSWORD:
      from_secret: DockerHubPassword
  settings:
    username: boulundeasv
    password: $DOCKER_HUB_PASSWORD
    repo: boulundeasv/demo-website
    tags:
    - latest
    - main
    ssh-agent-key:
      from_secret: private_key

trigger:
  branch:
  - main