kind: pipeline
type: docker
name: default

trigger:
  event:
  - push
  branch:
  - main

steps:
- name: build
  image: alpine
  environment:
    DOCKER_HUB_PASSWORD:
      from_secret: docker_hub_password
  commands:
    - echo "The build number is:"
    - echo $DRONE_BUILD_NUMBER

- name: test
  image: mcr.microsoft.com/dotnet/sdk
  commands:
    - dotnet test --no-build --logger "trx;LogFileName=test-results.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

  # Store a file artifact
- name: store_artifact
  image: alpine
  commands:
    - echo "Storing artifact..."
    - echo "This is an artifact file." > /drone/src/artifact.txt

- name: docker
  image: plugins/docker
  settings:
    username: boulundeasv
    password:
      from_secret: docker_hub_password
    repo: boulundeasv/demo-website
    tags:
    - latest
    - ${DRONE_BUILD_NUMBER}
    - staging

artifact:
  path: /drone/src/artifact.txt

volumes:
  - name: shared-data
    path: /drone/src

---

kind: pipeline
type: docker
name: deploy

trigger:
  event:
    - promote

steps:
- name: docker
  image: plugins/docker
  settings:
    username: boulundeasv
    password:
      from_secret: docker_hub_password
    repo: boulundeasv/demo-website
    tags:
    - production