kind: pipeline
type: docker
name: default

steps:
# - name: test
#   image: mcr.microsoft.com/dotnet/sdk
#   commands:
#   - dotnet build
#   - dotnet test
# - name: deliver
#   image: docker:dind
#   commands:
#   - sleep 5 # give docker enough time to start
#   - docker ps -a
#   - docker run -d hello-world
#   - docker ps -a

steps:
- name: build
  image: alpine
  environment:
    DOCKER_HUB_PASSWORD:
      from_secret: docker_hub_password
  commands:
    - echo "The build number is:"
    - echo $DRONE_BUILD_NUMBER

- name: docker
  image: plugins/docker
  settings:
    username: boulundeasv
    password:
      from_secret: docker_hub_password
    repo: boulundeasv/demo-website
    tags:
    - latest
    - $DRONE_BUILD_NUMBER
    - staging

trigger:
  branch:
  - main