kind: pipeline
type: docker
name: default

trigger:
  event:
  - push
  branch:
  - main

steps:
- name: build
  image: alpine
  environment:
    DOCKER_HUB_PASSWORD:
      from_secret: docker_hub_password
  commands:
    - echo "The build number is:"
    - echo $DRONE_BUILD_NUMBER

- name: test
  image: mcr.microsoft.com/dotnet/sdk
  commands:
    - cd UnitTests/
    - dotnet add package coverlet.msbuild
    - cd ..
    - dotnet test /p:CollectCoverage=true /p:CoverletOutput=coverage /p:CoverletOutputFormat=opencover

- name: publish-coverage
  image: mcr.microsoft.com/dotnet/sdk:6.0
  environment:
    COVERALLS_REPO_TOKEN:
      from_secret: coveralls_token
  commands:
    - dotnet tool install -g coveralls.net
    - export PATH="$PATH:/root/.dotnet/tools"
    - csmacnz.Coveralls --opencover -i UnitTests/coverage.opencover.xml --jobId $DRONE_BUILD_NUMBER --commitId $DRONE_COMMIT_SHA --commitBranch $DRONE_COMMIT_BRANCH --commitAuthor "$DRONE_COMMIT_AUTHOR" --commitEmail "$DRONE_COMMIT_AUTHOR_EMAIL" --commitMessage "$DRONE_COMMIT_MESSAGE" --useRelativePaths

# - name: docker
#   image: plugins/docker
#   settings:
#     username: boulundeasv
#     password:
#       from_secret: docker_hub_password
#     repo: boulundeasv/demo-website
#     tags:
#     - latest
#     - ${DRONE_BUILD_NUMBER}
#     - staging 

# artifact:
#   path: /drone/src/artifact.txt

# volumes:
#   - name: shared-data
#     path: /drone/src

# ---

# kind: pipeline
# type: docker
# name: deploy

# trigger:
#   event:
#     - promote

# steps:
# - name: docker
#   image: plugins/docker
#   settings:
#     username: boulundeasv
#     password:
#       from_secret: docker_hub_password
#     repo: boulundeasv/demo-website
#     tags:
#     - production